version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: ./node_modules/.bin/eslint src/

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Add github to known hosts
          command: mkdir ~/.ssh;ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Reset git
          command: git config user.email "dankolbman@gmail.com";git config user.name "Dan Kolbman";git reset --hard
      - run:
          name: Bump npm version
          command: git config user.email "dankolbman@gmail.com";git config user.name "Dan Kolbman";npm version from-git
      - run:
          name: Push back to github
          command: git config user.email "dankolbman@gmail.com";git config user.name "Dan Kolbman";git push -q https://${GITHUB_TOKEN}@github.com/kids-first/kf-uikit.git master
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
